### ISSUE TITLE
Serializing member objects

### ISSUE THREAD

**Issue by afpatmin** [dart-lang/json_serializable#105]
In the example.dart file, class Person has a List of Orders with both classes annotated as serializable.
However the member List<Order> doesn't get serialized in Person.toJson(), is that intentional?

```dart
Map<String, dynamic> toJson() {
    var val = <String, dynamic>{
      'firstName': firstName,
    };

    void writeNotNull(String key, dynamic value) {
      if (value != null) {
        val[key] = value;
      }
    }

    writeNotNull('middleName', middleName);
    val['lastName'] = lastName;
    val['date-of-birth'] = dateOfBirth.toIso8601String();
    val['last-order'] = lastOrder?.toIso8601String();
    val['orders'] = orders; // <-- Shouldn't this be: val['orders'] = orders.toJson(); 
    return val;
  }
```

**Comment by afpatmin** [comment]
Nevermind! found this solution: dart-lang/json_serializable#57

**Comment by Aldo111** [comment]
Is there a better way to generate a map instead of doing JSON.decode(JSON.encode(entity)); ? I'm using mongo-dart and when inserting data, just JSON.encode is not useful since it generates a string and I'm not sure if doing JSON.decode(JSON.encode(..)) is great especially if you have frequent operations and potentially big json/entity sizes?

**Comment by zoechi** [comment]
Have you tried `entity.toJson()`. I haven't tried `json_serializable` myself, but from having a quick look at the example code it should work.
