### ISSUE TITLE
Deserialize concrete subtypes of abstract class via type in data

### ISSUE THREAD

**Issue by denkuy** [dart-lang/json_serializable#369]
I'm looking for feedback/suggestions on how to make this more usable for general use and/or if this is interesting.

I got it working for our specific use case using those changes:
https://github.com/denkuy/json_serializable/commit/13ae7e23402feafed2a2619d002057afb5fe5cc6

## Scenario
We have an abstract class `Message` that should be (de-)serialized into a specific concrete subclass. We put a specific key into the generated Map but this is transparent to the actual inherited model classes (they don't contain a field for this)

## When to apply this generator pattern
Currently I apply this pattern to all abstract classes.

## Look for subtypes by scanning the abstract classes' library
This might be a limitation of the build system. Can I scan for subclasses in a different way? [relevant code](https://github.com/denkuy/json_serializable/commit/13ae7e23402feafed2a2619d002057afb5fe5cc6#diff-27ed7c8afac5e8f656cb4a40daafa079R45)

## Determine the class name
It is currently [hard coded](https://github.com/denkuy/json_serializable/commit/13ae7e23402feafed2a2619d002057afb5fe5cc6#diff-27ed7c8afac5e8f656cb4a40daafa079R49) to look for the value of the key `Command`. Where should this be configured? In `@JsonSerializable` of the abstract class?

We use the difference between the parent class name and the child class name. `abstract class Message` and `class SomeMessage extends Message` will use the key `Some`. I thought about adding a (const) Function somewhere that can generate this name off the class name (+ the base class name?)

## abstract base class

```dart
@JsonSerializable()
abstract class Message {
  Message();
  
  // use the modified "look for key" fromJson of Message
  factory Message.fromTypedJson(Map<String, dynamic> json) =>
      _$MessageFromJson(json); // generated impl below

  // use the modified "add type key" of Message
  Map<String, dynamic> toTypedJson() =>
    _$MessageToJson(this); // generated impl below

  // make subclasses implement toJson() to get its Map
  Map<String, dynamic> toJson();
}
```

The concrete class should extend `Message` and implement `toJson` and `factory fromJson` as usual. Here is an excerpt of the generated code for `Message`, if a subclass `SomeMessage` exists.

```dart
Message _$MessageFromJson(Map<String, dynamic> json) {
  switch (json["Command"] as String) {
    case "Some":
      return SomeMessage.fromJson(json);
    default:
      throw Exception("Unknown subtype");
  }
}

String _$MessageGetConcreteType(Message instance) {
  if (instance is SomeMessage) return "Some";
  throw Exception("Unknown subtype");
}

Map<String, dynamic> _$MessageToJson(Message instance) =>
    instance.toJson()..addAll({"Command": _$MessageGetConcreteType(instance)});
```

## Usage
```dart
// encode with type key
var some = SomeMessage();
var keyedJson = Message.toTypedJson(some);

// decode from type key
var json = <String, dynamic>{"Command": "Some"};
var instance = Message.fromTypedJson(json);
assert(instance is SomeMessage);
```

This works for the defailt config and it is not tested against other configuration setups like when using wrappers etc.

**Comment by kevmoo** [comment]
Would you create a pull request with https://github.com/denkuy/json_serializable/commit/13ae7e23402feafed2a2619d002057afb5fe5cc6 – and add tests to show the modified output?

I'm nervous about the complexity this would add – but open to discuss

**Comment by johnfriedrich** [comment]
Hello, seems like I am bit late to the party, but we do plan a similar system. In our case its an abstract Model class that can have hundreds of different direct subtypes. Was support added for such setup during the lasty ear? Couldn't find something in documentation though. Maybe you guys found a proper solution!

**Comment by ElteHupkes** [comment]
I haven't been able to find something that supports this without manually tracking the subtypes from the supertype in order to call `fromJson` on them. Ideally the supertype would have no knowledge of its implementers, and its `fromJson()` factory would call them correctly anyway.

The problem is probably that in order to generate an exhaustive factory method that depends on some `type` property, the code generator needs to scan every file in the `lib` folder for child classes that are serializable. That's not impossible, but I imagine it could be slow and, depending on how `build` generates its dependency graphs, might not always pick up changes when you expect it to. 

With those caveats in mind, I think I could probably write a source generator that does this. Let's say for instance we introduce two new annotations:
- `JsonFactory(String typeField)`
- `JsonImplementation(String type)`

We could then have something like:
```dart
@JsonFactory("brand")
class Car {
  final String brand;
  Car(this.brand);
  
  factory Car.fromJson(Map<String, dynamic> map) => _$CarFromJson(map);
}

@JsonSerializable(createToJson: false)
@JsonImplementation(Toyota.typeBrand)
class Toyota extends Car {
  static const typeBrand = "toyota";

  Toyota(String brand) : super(typeBrand);
  
  factory Toyota.fromJson(Map<String, dynamic> map) => _$ToyotaFromJson(map);
}

@JsonSerializable(createToJson: false)
@JsonImplementation(Mercedes.typeBrand)
class Mercedes extends Car {
  static const typeBrand = "mercedes";

  Mercedes(String brand) : super(typeBrand);

  factory Mercedes.fromJson(Map<String, dynamic> map) => _$MercedesFromJson(map);
}
```

After encountering `JsonFactory`, the code generator would scan for classes that extend `Car` which are both annotated with `JsonImplementation` and have a `fromJson(Map<String, dymamic>)` constructor. It would then generate:

```dart
Car _$CarFromJson(Map<String, dynamic> map) {
  switch (map["brand"] as String) {
    case "toyota":
      return Toyota.fromJson(map);
    case "mercedes":
      return Mercedes.fromJson(map);
    default:
      throw StateError("Unknown type ${map['brand']} when deserializing type `Car`.");
  }
}
```

I don't currently have a use case complicated enough to warrant getting into this to deeply, but I do think I have a general idea how this could be achieved, plus a prototype that takes some of the earliest steps. If somebody wants to pick this up I'd be glad to help. I have a few hours of Googling experience with `build` so I'm basically an expert 😛.

**Comment by levydanqc** [comment]
@ElteHupkes Did you ever found a way to implement this please ?

**Comment by ElteHupkes** [comment]
@levydanqc No further than I alluded to in my last comment unfortunately. As far as I'm aware it doesn't exist, and I never got around to implementing it either.
