### ISSUE TITLE
Is there any way to show which variable throws X is not a subtype of type Y

### ISSUE THREAD

**Issue by skyberk** [dart-lang/json_serializable#584]
I am getting sometimes "X is not a subtype of type Y". It easy to fix this issue with change variable type. But i have to do look carefully which variable throws this exception one by one. Is there any way getting this exception with caused variable name.

**Comment by kevmoo** [comment]
I need to see a code example of when this is happening...

**Comment by kevmoo** [comment]
Is this during code generation? Or when running to/from JSON?

**Comment by vipinagrahari** [comment]
@kevmoo  We also face the similar issue. 

consider the following error during deserialization due to incorrect type of data in json. 
```

Unhandled exception:
type 'String' is not a subtype of type 'int' in type cast
#0 _$JsonObjectFromJson
package:serializer_fail/json.g.dart:10
#1 new JsonObject.fromJson
package:serializer_fail/json.dart:11
#2 calculate
package:serializer_fail/serializer_fail.dart:7
#3 main
../bin/main.dart:4
#4 _startIsolate. (dart:isolate-patch/isolate_patch.dart:298:32)
```


In the above error we see that  **type 'String' is not a subtype of type 'int' in type cast**. However it is not mentioned which String value it is. It becomes really difficult to find the exact key which is breaking in a long json response. 

It would helpful if we can get error with value of json key which is incorrect.
e.g.   value "<string_json_value_here>" of type 'String' is not a subtype of type 'int' in type cast.

**Comment by skyberk** [comment]
@vipinagrahari thanks for helpful explanation, I have exactly same case with @vipinagrahari could you add failed variable name inside exception message @kevmoo ?

**Comment by kevmoo** [comment]
Use checked: true –
https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/checked.html
